stages:
  - build
  - upload
  - deploy

include:
  - project: 'devops/ci-templates'
    file: 'backend-nestjs.yml'

build:
  extends: .build_template

upload:
  extends: .upload_template

deploy:
  extends: .deploy_template
